version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: trend_data_etl_db
    environment:
      POSTGRES_DB: trend_data_etl
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
      TIMESCALEDB_TELEMETRY: off
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]

  redis:
    image: redis:7-alpine
    container_name: trend_data_etl_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  timescale_data:
  redis_data:
