services:
  - type: web
    name: trend-data-etl-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn scripts.quick_start_demo:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: trend-data-etl-db
          property: connectionString
      - key: QUALITY_THRESHOLD
        value: "90"
      - key: DATABASE_DEBUG
        value: "false"

databases:
  - name: trend-data-etl-db
    plan: starter
    databaseName: trend_data_etl
    user: etl_user