services:
  - type: web
    name: trend-data-etl-api
    env: python
    plan: free  # Start free, upgrade as needed
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: trend-data-etl-db
          property: connectionString
      - key: QUALITY_THRESHOLD
        value: 90

databases:
  - name: trend-data-etl-db
    plan: starter  # $7/month
    databaseName: trend_data_etl
    user: etl_user